### ISSUE TITLE
Critical features

### ISSUE THREAD

**Issue by HTInnovation** [Hung-Thinh-Innovation/VFastPunct#1]
Please add these following features - this is critical:
* md5sum verification for downloaded file and re-downloading file if the downloaded file is broken.
* add "Loading..." when loading model since this stuff is extremely slow.

**Comment by datnnt1997** [comment]
All features you need were updated. Please check this commit: https://github.com/Hung-Thinh-Innovation/VFastPunct/commit/2a5d4bbb467fd213ae3882e68d87576e9ec58692
